version: "3.7"

services:
    
    http:
        image: bayrell/cloud_router_http:0.1.0-20201130_170728
        hostname: "{{.Service.Name}}.{{.Task.ID}}.local"
        volumes:
            - "router_data:/data"
            - "../files/root/router.php:/root/router.php"
        env_file:
            - env.conf
        deploy:
            replicas: 1
            endpoint_mode: dnsrr
            update_config:
                parallelism: 1
                failure_action: rollback
                delay: 5s
            restart_policy:
                condition: "on-failure"
                delay: 10s
                window: 120s
            placement:
                constraints:
                    - node.labels.name == docker0
        networks:
            - cloud_router
        ports:
          - target: 80
            published: 80
            protocol: tcp
            mode: host
        logging:
            driver: journald

volumes:
    router_data:

networks:
    
    cloud_router:
        external: true
