version: "3.7"

services:

    cloud_router:
        image: bayrell/cloud_router:20200928_150202
        hostname: "{{.Service.Name}}.{{.Task.ID}}.local"
        volumes:
            - "cloud_router_data:/data"
            - "./router/root/router.php:/root/router.php"
        env_file:
            - common.env
        environment:
            DNS_RESOLVER: 127.0.0.11
            SYSTEM_PANEL: cloud_os_system_panel
            SYSTEM_DOMAIN: raspa.local
        ports:
            - 80:80
            - 443:443
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                failure_action: rollback
                delay: 5s
            restart_policy:
                condition: "on-failure"
                delay: 10s
                window: 120s
            placement:
                constraints:
                    - node.role == manager
        networks:
            - balancer
        logging:
            driver: journald
            

volumes:
    cloud_router_data:

networks:
    
    balancer:
        external: true

